name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: kill last process
        run: |
          pkill SpellingBeeBot
      - name: Activate venv
        run: |
          source .venv/bin/activate
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Launch main.py via nohup
        run : |
          nohup python3 main.py >/dev/null 2>&1 &